apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-cleaner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/bryanpaget/namespace-cleaner.git"
    targetRevision: main
    path: helm/namespace-cleaner
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: namespace-cleaner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
