apiVersion: batch/v1
kind: CronJob
metadata:
  name: namespace-cleaner
  namespace: bryan-paget
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleaner
              image: artifactory.cloud.statcan.ca/docker-mcr/azure-cli
              command: ["/bin/sh", "-c"]
              args:
                - apk add jq && ./namespace-cleaner.sh
              envFrom:
                - secretRef:
                    name: azure-creds
              volumeMounts:
                - name: script
                  mountPath: /namespace-cleaner.sh
                  subPath: namespace-cleaner.sh
                - name: config
                  mountPath: /etc/cleaner-config
              resources:
                limits:
                  memory: "256Mi"
                  cpu: "500m"
          volumes:
            - name: script
              configMap:
                name: namespace-cleaner-script
                defaultMode: 0744 # Makes script executable
            - name: config
              configMap:
                name: namespace-cleaner-config
          restartPolicy: Never
