name: Namespace Cleaner Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          version: "v0.20.0"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bash  # Ensure bash is available

      - name: Run test suite
        run: |
          make test
          make clean  # Cleanup after successful test

      - name: Debug on failure
        if: ${{ failure() }}
        run: |
          echo "=== Cluster State ==="
          kubectl get ns,configmaps -owide
          echo "=== Cleaner Logs ==="
          cat /proc/1/fd/1
