name: Namespace Cleaner Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Run full test suite
        run: |
          make test  # Applies configs → runs cleaner → verifies results
          make clean  # Cleanup after test

      - name: Debug on failure
        if: ${{ failure() }}
        run: |
          kubectl get ns -owide
          kubectl get configmaps -owide
