name: Namespace Cleaner Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Cleanup previous test
        run: |
          kubectl delete ns test-valid-user test-invalid-user test-expired-ns --ignore-not-found
          kubectl delete configmap namespace-cleaner-test-users --ignore-not-found

      - name: Deploy test resources
        run: |
          kubectl apply -f tests/test-config.yaml
          kubectl apply -f tests/test-cases.yaml

      - name: Run tests
        env:
          TEST_MODE: "true"
        run: |
          chmod +x namespace-cleaner.sh
          ./namespace-cleaner.sh

      - name: Verify results
        run: |
          # Function to check namespace existence with retries
          check_namespace() {
            local ns=$1
            local should_exist=$2
            local attempts=0
            local max_attempts=5

            while [ $attempts -lt $max_attempts ]; do
              exists=$(kubectl get ns $ns -o name 2>/dev/null | wc -l)

              if [ $should_exist = true ] && [ $exists -eq 1 ]; then
                return 0
              elif [ $should_exist = false ] && [ $exists -eq 0 ]; then
                return 0
              fi

              sleep 5
              attempts=$((attempts+1))
            done

            return 1
          }

          # Check valid namespace remains
          if ! check_namespace test-valid-user true; then
            echo "::error::Valid namespace was deleted"
            exit 1
          fi

          # Check invalid namespace was deleted
          if check_namespace test-invalid-user true; then
            echo "::error::Invalid namespace not deleted"
            exit 1
          fi

          # Check expired namespace was deleted
          if check_namespace test-expired-ns true; then
            echo "::error::Expired namespace not deleted"
            exit 1
          fi

          echo "All tests passed!"
          kubectl get ns
