name: Namespace Cleaner Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Cleanup previous test
        run: |
          kubectl delete ns test-valid-user test-invalid-user test-expired-ns --ignore-not-found
          kubectl delete configmap namespace-cleaner-test-users --ignore-not-found

      - name: Deploy test resources
        run: |
          kubectl apply -f tests/test-config.yaml
          kubectl apply -f tests/test-cases.yaml

      - name: Run tests
        env:
          TEST_MODE: "true"
        run: |
          chmod +x namespace-cleaner.sh
          ./namespace-cleaner.sh

      - name: Verify results
        run: |
          # Wait for finalization
          sleep 20

          # Check final states
          kubectl get ns -o wide > namespace-status.txt

          # Validate test-valid-user exists
          grep -q 'test-valid-user' namespace-status.txt || (echo "Valid namespace missing" && exit 1)

          # Validate test-invalid-user deleted
          grep -q 'test-invalid-user' namespace-status.txt && (echo "Invalid namespace still exists" && exit 1)

          # Validate test-expired-ns deleted
          grep -q 'test-expired-ns' namespace-status.txt && (echo "Expired namespace still exists" && exit 1)

          echo "All tests passed!"
          cat namespace-status.txt
